<?php

/**
 * @file
 * Provides custom implementation blocks and Ctools plugins.
 */
// Define custom block delta.
define('DRUPALCAMPCR_LAST_LOGIN_DELTA', 'drupalcampcr_last_login');

/**
 * Implements hook_block_info().
 */
function drupalcampcr_block_info() {

  // Definition of custom block.
  $blocks['drupalcampcr_last_login'] = array(
    'info' => t('Users last login'),
    'cache' => DRUPAL_CACHE_PER_USER,
    'status' => TRUE,
    'region' => 'highlighted',
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function drupalcampcr_block_configure($delta = '') {

  $form = array();
  switch ($delta) {
    // Check current delta block.
    case DRUPALCAMPCR_LAST_LOGIN_DELTA:
      $form['drupalcampcr_login_message_block'] = array(
        '#type' => 'textfield',
        '#title' => t('Define a message to show up.'),
        '#default_value' => variable_get('drupalcampcr_login_message_block', NULL),
      );
      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function drupalcampcr_block_save($delta = '', $edit = array()) {

  switch ($delta) {
    // Check current delta block.
    case DRUPALCAMPCR_LAST_LOGIN_DELTA:
      variable_set('drupalcampcr_login_message_block', $edit['drupalcampcr_login_message_block']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function drupalcampcr_block_view($delta = '') {

  $block = array();
  switch ($delta) {
    // Check current delta block.
    case DRUPALCAMPCR_LAST_LOGIN_DELTA:
      // Skip if user is anonymous.
      if (user_is_anonymous()) {
        break;
      }

      // Define block content.
      $block['subject'] = t('Last login');
      $block['content'] = array(
        '#theme' => 'drupalcampcr_last_login',
        '#message' => variable_get('drupalcampcr_login_message_block', NULL),
      );
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function drupalcampcr_theme() {
  return array(
    'drupalcampcr_last_login' => array(
      'variables' => array(
        'account' => NULL,
        'message' => NULL,
      ),
    ),
  );
}

/**
 * Callback theme function to format last login.
 */
function theme_drupalcampcr_last_login($variables) {

  // Retrieve account given by parameter, otherwise
  // load current user by helper function.
  $account = (!empty($variables['account'])) ?
      $variables['account'] : user_uid_optional_load();

  // Retrieve message variable.
  $message = (!empty($variables['message'])) ?
      $variables['message'] : NULL;

  // Define last logged in date "format_date"
  // by default retrieve current user timezone.
  $date_login = format_date($account->login);
  $output['wrapper'] = array(
    '#type' => 'fieldset',
    '#title' => ' ',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#attributes' => array(
      'class' => array(
        'drupalcampcr-wrapper-block-account-logged',
      ),
    ),
  );
  $output['wrapper']['info'] = array(
    '#theme' => 'html_tag',
    '#tag' => 'div',
    '#value' => "You last logged in at {$date_login}. {$message}",
    '#attributes' => array(
      'class' => array(
        'drupalcampcr-block-account-login',
      ),
    ),
    '#value_prefix' => '<strong>',
    '#value_suffix' => '</strong>',
  );
  return render($output);
}
